/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/shared/Navbar/Navbar";
import Footer from "@/components/shared/Footer/Footer";
import ClientWrapper from "@/components/ClientWrapper";
import StoreProviders from "../redux/StoreProviders";
import AppInitializer from "@/redux/features/appInitilaze/Appintialize";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <StoreProviders>
          {/* 🔥 Bootstrap auth + subscription once */}
          <AppInitializer />

          <Navbar />

          <ClientWrapper>{children}</ClientWrapper>
          <Toaster position="top-center" />
          <Footer />
        </StoreProviders>
      </body>
    </html>
  );
}
